const words = [
  { en: 'hello', pt: 'olá' },
  { en: 'goodbye', pt: 'tchau' },
  { en: 'please', pt: 'por favor' },
  { en: 'thank you', pt: 'obrigado' },
  { en: 'water', pt: 'água' },
  { en: 'food', pt: 'comida' },
  { en: 'help', pt: 'ajuda' },
  { en: 'yes', pt: 'sim' },
  { en: 'no', pt: 'não' },
  { en: 'morning', pt: 'manhã' },
  { en: 'afternoon', pt: 'tarde' },
  { en: 'night', pt: 'noite' },
  { en: 'today', pt: 'hoje' },
  { en: 'tomorrow', pt: 'amanhã' },
  { en: 'yesterday', pt: 'ontem' },
  { en: 'house', pt: 'casa' },
  { en: 'car', pt: 'carro' },
  { en: 'book', pt: 'livro' },
  { en: 'sun', pt: 'sol' },
  { en: 'moon', pt: 'lua' },
  { en: 'world', pt: 'mundo' },
  { en: 'friend', pt: 'amigo' },
  { en: 'family', pt: 'família' },
  { en: 'love', pt: 'amor' },
  { en: 'happy', pt: 'feliz' },
  { en: 'sad', pt: 'triste' },
  { en: 'beautiful', pt: 'bonito' },
  { en: 'ugly', pt: 'feio' },
  { en: 'big', pt: 'grande' },
  { en: 'small', pt: 'pequeno' },
  { en: 'hot', pt: 'quente' },
  { en: 'cold', pt: 'frio' },
  { en: 'eat', pt: 'comer' },
  { en: 'drink', pt: 'beber' },
  { en: 'sleep', pt: 'dormir' },
  { en: 'go', pt: 'ir' },
  { en: 'see', pt: 'ver' },
  { en: 'speak', pt: 'falar' },
  { en: 'read', pt: 'ler' },
  { en: 'write', pt: 'escrever' },
  { en: 'one', pt: 'um' },
  { en: 'two', pt: 'dois' },
  { en: 'three', pt: 'três' },
  { en: 'four', pt: 'quatro' },
  { en: 'five', pt: 'cinco' },
  { en: 'money', pt: 'dinheiro' },
  { en: 'time', pt: 'tempo' },
  { en: 'work', pt: 'trabalho' },
  { en: 'school', pt: 'escola' },
  { en: 'city', pt: 'cidade' },
  { en: 'country', pt: 'país' },
  { en: 'left', pt: 'esquerda' },
  { en: 'right', pt: 'direita' },
  { en: 'up', pt: 'cima' },
  { en: 'down', pt: 'baixo' },
  { en: 'open', pt: 'aberto' },
  { en: 'closed', pt: 'fechado' }
];

export default words;